name: dadi
description: Decentralized Autonomous Dildo Interface
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web3: ^2.1.9
  web_socket_channel: ^2.4.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.2
  web3dart: ^2.7.1
  convert: ^3.1.1
  crypto: ^3.0.3
  logging: ^1.2.0
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
